/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controler.Controler;
import domain.Veterinar;
import frm.appointment.FormAppointment;


import frm.patient.FrmPatient;
import frm.patient.FrmSearch;
import java.awt.Color;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import session.Session;
import usecase.UseCase;

/**
 *
 * @author MSWINDOWS
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        populateForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPatient = new javax.swing.JMenu();
        MINew = new javax.swing.JMenuItem();
        MISearch = new javax.swing.JMenuItem();
        ManuAppointment = new javax.swing.JMenu();
        MINewAp = new javax.swing.JMenuItem();
        MISearchAp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vet"));

        jLabel1.setText("Current vet:");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap(633, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnLogout)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        MenuPatient.setText("Patient");

        MINew.setText("New");
        MINew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINewActionPerformed(evt);
            }
        });
        MenuPatient.add(MINew);

        MISearch.setText("Search");
        MISearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISearchActionPerformed(evt);
            }
        });
        MenuPatient.add(MISearch);

        jMenuBar1.add(MenuPatient);

        ManuAppointment.setText("Appointment");

        MINewAp.setText("New");
        MINewAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINewApActionPerformed(evt);
            }
        });
        ManuAppointment.add(MINewAp);

        MISearchAp.setText("Search");
        MISearchAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISearchApActionPerformed(evt);
            }
        });
        ManuAppointment.add(MISearchAp);

        jMenuBar1.add(ManuAppointment);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
       logoutVet();
        
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void MINewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINewActionPerformed
        // TODO add your handling code here:
         Session.getInstance().setCurrentUseCase(UseCase.UC_NEW_PATIENT);
        JDialog frmNewPatient = new FrmPatient(null, true);
        frmNewPatient.pack();
        frmNewPatient.setVisible(true);
        
        
    }//GEN-LAST:event_MINewActionPerformed

    private void MISearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISearchActionPerformed
        // TODO add your handling code here:
         Session.getInstance().setCurrentUseCase(UseCase.UC_SEARCH_PATIENTS);
        JDialog frmSearchPatients = new FrmSearch(this, true);
        frmSearchPatients.pack();
        frmSearchPatients.setVisible(true);
    }//GEN-LAST:event_MISearchActionPerformed

    private void MINewApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINewApActionPerformed
        // TODO add your handling code here:
         Session.getInstance().setCurrentUseCase(UseCase.UC_NEW_APPOINTMENT);
        JDialog frmNewAppointment = new FormAppointment(this, true);
        frmNewAppointment.pack();
        frmNewAppointment.setVisible(true);
        
    }//GEN-LAST:event_MINewApActionPerformed

    private void MISearchApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISearchApActionPerformed
        // TODO add your handling code here:
         Session.getInstance().setCurrentUseCase(UseCase.UC_SEARCH_APPOINTMENT);
        JDialog frmSearchAppointment = new FrmSearch(this, true);
        frmSearchAppointment.pack();
        frmSearchAppointment.setVisible(true);
    }//GEN-LAST:event_MISearchApActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
       logoutVet();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MINew;
    private javax.swing.JMenuItem MINewAp;
    private javax.swing.JMenuItem MISearch;
    private javax.swing.JMenuItem MISearchAp;
    private javax.swing.JMenu ManuAppointment;
    private javax.swing.JMenu MenuPatient;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCurrent;
    // End of variables declaration//GEN-END:variables

    private void populateForm() {
          populateCurrentDentist();
        setScreenCenter();
        
        //setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    private void populateCurrentDentist() {
        Veterinar vet=Session.getInstance().getCurrentVet();
        lblCurrent.setText("   "+vet.getImePrezimeVeterinara());
    }

    private void setScreenCenter() {
       setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        Panel.setBackground(Color.WHITE);
    }
    private void logoutVet(){
        int response=JOptionPane.showConfirmDialog(null, "Do you want to log out?", "Confirm",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            Veterinar  v = Session.getInstance().getCurrentVet();
            try {
                Controler.getInstance().logOut(v);
                JOptionPane.showMessageDialog(null, "You are logged out!");
                System.exit(0);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    
    }
}
